spring.application.name=AnuFood

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_tkx3TyoM
spring.datasource.username=u_ScRNff
spring.datasource.password=DQqFaqOje0Sn
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

razorpay.key=rzp_test_VxDXNU2LjZXDcy
razorpay.secret=9fkr0wlwdR3Kq67ghwFEHtIr

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anufood@gmail.com
spring.mail.password=your_app_password_here
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

server.port=8080

file.upload-dir=uploads/images/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=10MB
